WARNING:django.request:Not Found: /favicon.ico
ERROR:root:[{'id': 1, 'name': 'Monster incorp.', 'address': 'a1', 'city': 'a2', 'postal_code': 'a3', 'administrative_unit': 'gregt regw', 'flat_number': 43, 'nip': 12345678, 'krs': 12345678, 'description': 'g rf hreh etrhrtehe', 'org_status': 0, 'rendered': False, 'mail': 'gg@gmail.com', 'owner_id': 1}]
INFO:django.utils.autoreload:C:\Users\Shurik\PycharmProjects\Old_python_project\Project\socialmerge\mergeservice\models.py changed, reloading.
